### ISSUE TITLE
(node:30846) [DEP0005] DeprecationWarning:

### ISSUE THREAD

**Issue by chenweibo** [icetee/node-ftp#11]
How do I need to deal with  

internal/process/warning.js:18 (node:30846) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Follow the example to run normally, but this error makes me uncomfortable.

**Comment by icetee** [comment]
The code has already [change](https://github.com/icetee/node-ftp/blob/master/lib/connection.js#L49), maybe the bug in `xregexp` package. I'm looking at it soon, thanks.

**Comment by chenweibo** [comment]
Thank you very much for your reply. I hope this project will run well.
Before using mscdex/node-ftp, many problems have not been fixed. Many things have been solved for your project. thinks

**Comment by icetee** [comment]
I think resolved this issue. You may have used an earlier version of anno.
