### ISSUE TITLE
Uncaught ReferenceError: reentry is not defined

### ISSUE THREAD

**Issue by icetee** [icetee/node-ftp#3]
Related of https://github.com/icetee/remote-ftp/issues/1078

**Comment by cctv1237** [comment]
looks like an code issue, reentry is not defined in this scope. So when ever goes into
```js
if (self._socket && ip !== self._socket.remoteAddress) 
```
it will crash

**Comment by cctv1237** [comment]
https://github.com/realtymaps/promise-ftp is using it as a dependency.

**Comment by icetee** [comment]
Fixed https://github.com/icetee/node-ftp/pull/15 PR.

**Comment by icetee** [comment]
Fixed it from the next release `v1.0.7`. Thanks to everyone.
